# Generated by Django 5.0.4 on 2024-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('addmission_no', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('event', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('applicant_photo', models.ImageField(blank=True, upload_to='applicant_photo/')),
                ('applicant_sign', models.ImageField(blank=True, upload_to='applicant_sign/')),
                ('guardian_sign', models.ImageField(blank=True, upload_to='guardian_sign/')),
                ('applicant_doc_1', models.FileField(blank=True, upload_to='applicant_file_1/')),
                ('applicant_doc_2', models.FileField(blank=True, upload_to='applicant_file_2/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
