# Generated by Django 5.0.4 on 2024-07-02 06:31

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ourheroes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionform',
            options={'verbose_name_plural': 'Admission Forms'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='ourheroes',
            options={'verbose_name_plural': 'Our Heroes'},
        ),
        migrations.AlterField(
            model_name='ourheroes',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='our_heroes/'),
        ),
    ]
